module(
    name = "notepadqq",
    version = "0.0.0",
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_qt", version = "0.0.6")
single_version_override(
    module_name = "rules_qt",
    version = "0.0.6",
    patches = ["//third_party:rules_qt-0.0.6-webengine.patch"],
    patch_strip = 1,
)

http_archive(
    name = "uchardet",
    urls = ["https://github.com/BYVoid/uchardet/archive/refs/tags/v0.0.5.tar.gz"],
    sha256 = "7c5569c8ee1a129959347f5340655897e6a8f81ec3344de0012a243f868eabd1",
    strip_prefix = "uchardet-0.0.5",
    build_file = "//third_party:uchardet.BUILD.bazel",
)


qt = use_extension("@rules_qt//extension:qt.bzl", "fetch")
qt.install(
    name = "qt_linux_x86_64",
    build_file = "@rules_qt//extension:qt/6.8.3/linux_x86_64.BUILD",
    os = "linux",
    version = "6.4.0", # Use 6.4.0 to avoid the 6.8.3 web engine issue on Linux.
)
qt.install(
    name = "qt_windows_x86_64",
    build_file = "@rules_qt//extension:qt/6.8.3/windows_x86_64.BUILD",
    os = "windows",
    version = "6.8.3",
    windows_architecture = "win64_msvc2022",
)
qt.install(
    name = "qt_mac_aarch64",
    build_file = "@rules_qt//extension:qt/6.8.3/mac_aarch64.BUILD",
    os = "macos",
    version = "6.8.3",
)
use_repo(qt, "qt_linux_x86_64", "qt_mac_aarch64", "qt_windows_x86_64")

register_toolchains(
    "@rules_qt//tools:all",
)