name: Build and Test CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  notepadqq-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
    - name: Build
      run: bazelisk build //src/ui:main

  notepadqq-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
    - name: Build
      run: bazelisk build //src/ui:main

  notepadqq-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v3
    - name: Build
      run: bazelisk build //src/ui:main